Repository MOT-Multi-Functional-Bot/MOT-Multi-Functional-Bot, pull requests merged in 2022-03, with the labels that each got.

#18 Wordle dev into main
  .gitignore
  README.md
  main.py
  wordle/wordle.py
  wordle/wordle_commands.py
  wordle/wordlist.py
Labels: enhancement

#24 Wordle dev into main
  .gitignore
  games/wordle/exceptions.py
  games/wordle/wordle.py
  games/wordle/wordle_commands.py
  games/wordle/wordlist.py
  main.py
  main_commands.py
Labels: enhancement

#27 Moviegame dev
  MovieGame/moviegame.py
  MovieGame/moviequiz.py
  main.py
  main_commands.py
Labels: enhancement

#29 numbers-dev to dev
  games/numbergame/exceptions.py
  games/numbergame/numbergame.py
  games/numbergame/numbergame_commands.py
  main.py
  main_commands.py
Labels: enhancement

#31 Merge Dev into Main
  games/MovieGame/moviegame.py
  games/MovieGame/moviequiz.py
  games/numbergame/exceptions.py
  games/numbergame/numbergame.py
  games/numbergame/numbergame_commands.py
  main.py
Labels: enhancement

#36 added docker build
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement, DeployPackage

#39 Add Dockerfiles
  Dockerfile
  docker-compose.yml
Labels: enhancement

#40 Update Dev-Branch
  README.md
  conf.template.py
Labels: enhancement

#41 Dev into Moviegame-Dev
  Dockerfile
  README.md
  conf.template.py
  docker-compose.yml
  games/MovieGame/moviegame.py
  games/MovieGame/moviequiz.py
  games/numbergame/exceptions.py
  games/numbergame/numbergame.py
  games/numbergame/numbergame_commands.py
  main.py
  main_commands.py
Labels: enhancement

#46 Updated Readme into Main
  README.md
  conf.template.py
  docker-compose.yml
  games/MovieGame/moviegame.py
  main.py
  main_commands.py
Labels: enhancement

#47 Small fixes and improvements
  .gitignore
  Dockerfile
  README.md
  games/MovieGame/moviegame.py
  games/numbergame/numbergame.py
  games/numbergame/numbergame_commands.py
  games/wordle/wordle.py
  games/wordle/wordle_commands.py
  main.py
  main_commands.py
Labels: enhancement

#49 Multiple Fixes and improvements
  README.md
  docker-compose.yml
  games/MovieGame/moviequiz.py
  games/moviegame/moviegame_commands.py
  games/wordle/wordle.py
  games/wordle/wordle_commands.py
  main.py
  main_commands.py
Labels: enhancement

#51 Switch to english wordlist & fix even more typos
  games/moviegame/moviequiz.py
  games/wordle/wordle.py
  games/wordle/wordle_commands.py
  games/wordle/wordlist.py
  main_commands.py
Labels: enhancement

#54 Update README.md
  README.md
Labels: enhancement, good first issue

#64 formatting + small fixes
  games/moviegame/moviegame_commands.py
  games/moviegame/runninggames.py
  testing/test_moviegame/test_moviegame_commands.py
  testing/test_moviegame/test_moviegamechat.py
  testing/test_moviegame/test_moviegamesmessage.py
  testing/test_moviegame/test_moviegamesupdates.py
  testing/test_moviegame/test_moviequiz.py
  testing/test_numbergame/test_numbergame.py
  testing/test_numbergame/test_numbergame_commands.py
  testing/test_wordle/test_wordle.py
  testing/test_wordle/test_wordle_commands.py
Labels: enhancement

#66 fixed paths and loginput bug with testing
  games/moviegame/moviegame_commands.py
  testing/test_moviegame/test_moviegame_commands.py
  testing/test_moviegame/test_moviegamesmessage.py
Labels: enhancement

#68 Add unittests for numbergame
  games/numbergame/numbergame.py
  testing/test_numbergame/test_numbergame.py
  testing/test_numbergame/test_numbergame_commands.py
  testing/test_wordle/test_wordle.py
  testing/test_wordle/test_wordle_commands.py
Labels: enhancement

#67 Add TicTacToe & Unittests & small fixes
  .gitignore
  README.md
  games/README.md
  games/moviegame/moviegame_commands.py
  games/moviegame/runninggames.py
  games/numbergame/numbergame.py
  games/numbergame/numbergame_commands.py
  games/tictactoe/__init__.py
  games/tictactoe/helperfunctions.py
  games/tictactoe/tictactoe.py
  main.py
  main_commands.py
  testing/test_moviegame/test_moviegame_commands.py
  testing/test_moviegame/test_moviegamechat.py
  testing/test_moviegame/test_moviegamesmessage.py
  testing/test_moviegame/test_moviegamesupdates.py
  testing/test_numbergame/test_numbergame.py
Labels: enhancement

#69 Update Games Readme
  games/README.md
Labels: documentation

#70 Packageupdates
  games/README.md
Labels: enhancement, DeployPackage
